#pragma	once

enum	ET_UIGUID_INNER	//	��Ʈ�� ID
{
	BASIC_QUICK_SKILL_SLOT = NO_ID + 1,
	QUICK_SKILL_TRAY_OPEN_BUTTON,
	QUICK_SKILL_TRAY_TAB_WINDOW,
	LEFTTOP_CONTROL_GROUP,
	BASIC_INFO_VIEW,	
	MINIMAP,
	ESCMENU_OPEN,
	QBOX_BUTTON,
	GAME_MENU_OPEN_BUTTON,
	GAME_MENU,
	MINIPARTY_OPEN,
	BASIC_CHAT_BOX,
	CHARACTER_WINDOW,
	OPTION_HW_WINDOW,
	SKILL_WINDOW,
	ESC_MENU,
	PARTY_WINDOW,
	MARKET_WINDOW,
	INVENTORY_WINDOW,
	TRADE_WINDOW,
	TRADEINVENTORY_WINDOW,
	STORAGE_WINDOW,
	SKILL_WINDOW_TO_TRAY,
	MINIPARTY_WINDOW,	
	MINIPARTYLINK_WINDOW,
	ITEM_MOVE,
	PTOPMENU_WINDOW,
	DAMAGE_MAN,
	RANKING_DISPLAY,
	//Target Info
	TARGETINFO_DISPLAY,	
	TARGETINFO_DISPLAY_NPC,	
	TARGETINFO_DISPLAY_PLAYER,
	//CrowTarget Info	
	CROW_TARGET_INFO,
	CROW_TARGET_INFO_NPC,
	CROW_TARGET_INFO_PLAYER,
	
	PARTY_DISPLAY,
	
	NAME_DISPLAY_MAN,
	DIALOGUE_WINDOW,
	DIALOGUE_WINDOW_RENEWAL,
	HEADCHAT_MAN,
	ADMIN_MESSAGE_DISPLAY,
	CONFT_MODAL_WINDOW,
	MAPMOVE_DISPLAY,
	MAPMOVE_DISPLAY_DUMMY,
	PARTY_MODAL_WINDOW,
	HELP_WINDOW,
	ITEMSHOP_WINDOW,
	QUEST_WINDOW,
	CONFT_DISPLAY_MAN,
	INFO_DISPLAY,
	INFO_DISPLAY_EX,
	INFO_DISPLAY_EX_EX,
	QUEST_ALARM,
	WAITSERVER_DISPLAY,
	SIMPLE_HP,
	FRIEND_WINDOW,
	BUS_WINDOW,
	SKILL_TIME_DISPLAY,
	ACADEMY_CONFT_DISPLAY,
	BLOCK_PROGRAM_ALARM,
	BLOCK_PROGRAM_ALARM_DUMMY,
	ITEMBANK_WINDOW,
	VNGAINSYS_WINDOW,
	VNGAINSYS_GAUGE_WINDOW,
	LARGEMAP_WINDOW,
	MOBPREVIEW_WINDOW,
	STORAGE_CHARGE_CARD,
	REBIRTH_DIALOGUE,
	REBIRTH_WINDOW,
	PRIVATE_MARKET_WINDOW,
	PRIVATE_MARKET_MAKE,
	PRIVATE_MARKET_SELL_WINDOW,
	PRIVATE_MARKET_SHOW_MAN,
	CLUB_WINDOW,
	SUBMASTER_MAKE,
	SIMPLE_MESSAGE_MAN,
	CLUB_MAKE,
	SYSTEM_MESSAGE_WINDOW,
	SYSTEM_MESSAGE_WINDOW_DUMMY,
    QUESTION_ITEM_DISPLAY,
	CLUB_STORAGE_WINDOW,
	CONFT_CONFIRM,
	RECEIVE_NOTE_WINDOW,
	WRITE_NOTE_WINDOW,
	SMS_SEND_WINDOW,
	HAIRCOLORCARD_WINDOW,
	HAIRSTYLECARD_WINDOW,
	PETCOLORCARD_WINDOW,
	PETSTYLECARD_WINDOW,
	WARNING_MSG_WINDOW,
	COUNT_MSG_WINDOW,
	ITEM_REBUILD_WINDOW,	// ITEMREBUILD_MARK
	REBUILDINVENTORY_WINDOW,
	PET_WINDOW,
	PET_SKILL_WINDOW,
	PET_REBIRTH_DIALOGUE,  // Monster7j
	GAMBLE_DIALOGUE,
	GAMBLE_SELECT_DIALOGUE,
	GAMBLE_AGAIN_DIALOGUE,
	GAMBLE_ANIMATION_DIALOGUE,
	GAMBLE_RESULT_ODD_DIALOGUE,
	GAMBLE_RESULT_EVEN_DIALOGUE,
	KEY_SETTING_WINDOW,
	CHATMACRO_WINDOW,
	WEAPON_DISPLAY,
	BONUSTIME_EVENT_GAUGE,
	BONUSTIME_EVENT_DISPLAY,
	QUEST_HELPER_DISPLAY,
	VEHICLE_WINDOW,
	GENDER_CHANGE_WINDOW,
	THAI_CCAFE_MARK,
	GARBAGEINVENTORY_WINDOW,
    ITEM_GARBAGE_WINDOW,
	ITEM_SHOP_ICON_MAN,
	ITEM_SHOP_SEARCH_WINDOW,
	ITEM_SEARCH_RESULT_WINDOW,
	PETSKIN_MIX_IMAGE_WINDOW,
	ATTENDANCE_BOOK_WINDOW,
	FACE_CHANGE_WINDOW,
	MAP_REQUIRE_CHECK,
	CLUB_BATTLE_MODAL_WINDOW,
	TAXI_WINDOW,
	ITEM_MIX_WINDOW,
	ITEM_MIX_INVEN_WINDOW,
	GATHER_GAUGE,
	CDM_RANKING_DISPLAY,
	PK_NOTIFICATION,
	PK_COMBO_DISPLAY,

	/*itemfood system, Juver, 2017/05/25 */
	FITEMFACT_TIME_DISPLAY, 

	/*game stats, Juver, 2017/06/22 */
	GAMESTATS_DISPLAY, 

	/*npc shop, Juver, 2017/07/25 */
	NPC_SHOP_WINDOW, 

	/*item preview, Juver, 2017/07/27 */
	ITEMPREVIEW_WINDOW, 

	/*pet status, Juver, 2017/07/30 */
	PET_STATUS_INFO, 

	/*vehicle status, Juver, 2017/07/30 */
	VEHICLE_STATUS_INFO, 

	/*item link, Juver, 2017/07/31 */
	INFO_DISPLAY_ITEM_LINK, 
	INFO_DISPLAY_ITEM_LINK_EX, 

	/*vehicle booster system, Juver, 2017/08/11 */
	VEHICLE_BOOSTER_DISPLAY, 

	/*box contents, Juver, 2017/08/29 */
	INFO_BOX_CONTENTS,		

	/*system buffs, Juver, 2017/09/05 */
	SYSTEM_BUFF_TIME_DISPLAY,

	SLOTCOUNT_MSG_WINDOW,

	/* Competition UI, Juver, 2017/08/24 */
	COMPETITION_NOTIFY_BUTTON,
	COMPETITION_WINDOW,

	/* extra notice, Juver, 2017/08/24 */
	EXTRA_NOTICE, 

	/*pvp tyranny, Juver, 2017/08/25 */
	PVP_TYRANNY_TOWER_CAPTURE,
	PVP_TYRANNY_TOWER_PROGRESS,
	REBIRTH_DIALOGUE_TYRANNY,
	PVP_TYRANNY_TOWER_CAPTURE_NOTICE_SG,
	PVP_TYRANNY_TOWER_CAPTURE_NOTICE_MP,
	PVP_TYRANNY_TOWER_CAPTURE_NOTICE_PHX,
	PVP_TYRANNY_TOWER_2CAPTURE_NOTICE_SG,
	PVP_TYRANNY_TOWER_2CAPTURE_NOTICE_MP,
	PVP_TYRANNY_TOWER_2CAPTURE_NOTICE_PHX,
	PVP_TYRANNY_TOWER_2CAPTURE_NOTICE_OWN,
	PVP_TYRANNY_RANKINGS,
	PVP_TYRANNY_TOPRANKINGS,
	PVP_TYRANNY_BATTLE_START_NOTICE,
	PVP_TYRANNY_BATTLE_END_NOTICE,

	/*item exchange, Juver, 2017/10/12 */
	NPC_ITEM_EXCHANGE_WINDOW,

	/*product item, Juver, 2017/10/15 */
	PRODUCT_BUTTON,
	PRODUCT_WINDOW,
	PRODUCT_PROGRESS,

	/*student record ui, Juver, 2017/10/30 */
	STUDENT_RECORD_BUTTON,
	STUDENT_RECORD_WINDOW,
	/*Codex System, Jhoniex 2/14/2024 */
	STUDENT_CODEX_BUTTON,
	STUDENT_CODEX_WINDOW,

	/*activity system, Juver, 2017/11/05 */
	ACTIVITY_ITEM_WINDOW,

	/*quest ui, Juver, 2017/11/06 */
	MODERN_QUEST_WINDOW,

	/*charinfoview , Juver, 2017/11/11 */
	CHARACTER_INFO_VIEW_WINDOW,

	/*bike color , Juver, 2017/11/12 */
	BIKE_COLOR_WINDOW,

	/*pet skill info display, Juver, 2017/12/01 */
	/*dual pet skill, Juver, 2017/12/29 */
	PET_SKILL_INFO_DISPLAY,
	PET_SKILL_INFO_DISPLAY2,

	/*change scale card, Juver, 2018/01/03 */
	CHANGE_SCALE_WINDOW,

	/*item color, Juver, 2018/01/10 */
	ITEM_COLOR_WINDOW,

	/*change school card, Juver, 2018/01/12 */
	CHANGE_SCHOOL_WINDOW,

	/*equipment lock, Juver, 2018/01/13 */
	EQUIPMENT_LOCK_ENABLE_WINDOW,
	EQUIPMENT_LOCK_INPUT_WINDOW,
	EQUIPMENT_LOCK_RECOVER_WINDOW,

	/*storage lock, Juver, 2018/01/13 */
	STORAGE_LOCK_ENABLE_WINDOW,
	STORAGE_LOCK_INPUT_WINDOW,
	STORAGE_LOCK_RECOVER_WINDOW,

	/*inventory lock, Juver, 2018/01/13 */
	INVENTORY_LOCK_ENABLE_WINDOW,
	INVENTORY_LOCK_INPUT_WINDOW,
	INVENTORY_LOCK_RECOVER_WINDOW,

	/*item transfer card, Juver, 2018/01/18 */
	ITEM_TRANSFER_WINDOW,
	ITEM_TRANSFER_INVEN_WINDOW,

	/*school wars, Juver, 2018/01/19 */
	PVP_SCHOOLWARS_SCORE,
	REBIRTH_DIALOGUE_SCHOOLWARS,
	PVP_SCHOOLWARS_RANKINGS,
	PVP_SCHOOLWARS_TOPRANKINGS,
	PVP_SCHOOLWARS_BATTLE_START_NOTICE,
	PVP_SCHOOLWARS_BATTLE_END_NOTICE,

	/*pvp capture the flag, Juver, 2018/02/01 */
	REBIRTH_DIALOGUE_CAPTURE_THE_FLAG,
	PVP_CAPTURE_THE_FLAG_TOPRANKINGS,
	PVP_CAPTURE_THE_FLAG_BATTLE_START_NOTICE,
	PVP_CAPTURE_THE_FLAG_BATTLE_END_NOTICE,
	PVP_CAPTURE_THE_FLAG_SCORE,
	PVP_CAPTURE_THE_FLAG_RANKINGS,
	PVP_CAPTURE_THE_FLAG_HOLD_ICON,

	/* car, cart color, Juver, 2018/02/14 */
	CAR_COLOR_WINDOW,

	FINDER_BUTTON,
	/*PartySearch - Added By Bubu*/
	PARTYFINDER_WINDOW,
	PARTYFINDER_BUTTON,
	PARTYREQUEST_MODAL,

	SECURITY_WINDOW,

	//PANDORA
	PANDORA_BOX,	
	PANDORA_BUTTON,


	/*dmk14 ingame web*/
	ITEMMALL_WINDOW,
	ITEMMALL_BUTTON,

	PLAYER_RANKING_BUTTON,

	/////////////////////////////////////////////////////////////////////////////
	// LG-7 GlobalRanking
	GLOBAL_RANKING_WINDOW,
	GLOBAL_RANKING_BUTTON,
	/////////////////////////////////////////////////////////////////////////////

	/////////////////////////////////////////////////////////////////////////////
	// LG-7 CWRanking
	CW_RANKING_DISPLAY,
	/////////////////////////////////////////////////////////////////////////////
	
    ITEM_INFOR_TOOLTIP,
    ITEM_INFOR_TOOLTIP_WEAR,
	ITEM_INFOR_TOOLTIP_LINK,
	ITEM_INFOR_TOOLTIP_DURABILITY,
    SKILL_INFOR_TOOLTIP,
	SKILL_INFOR_TOOLTIP_MULTI,
	SKILL_INFOR_TOOLTIP_LINK,
	SKILL_INFOR_TOOLTIP_DELAY_ACTION,

	//	NOTE
	//		ID�� ��
	MODAL_WINDOW,
};
