add_library(Lib_ClientUI STATIC
    Interface/AcademyConftDisplay.cpp
    Interface/ActivityItemList.cpp
    Interface/ActivityItemListSlot.cpp
    Interface/ActivityItemWindow.cpp
    Interface/ActivityPage.cpp
    Interface/ActivityPageMain.cpp
    Interface/ActivityPageMainSlot.cpp
    Interface/AdminMessageDisplay.cpp
    Interface/AttendanceBookWindow.cpp
    Interface/AudioOption.cpp
    Interface/BasicAnimationBox.cpp
    Interface/BasicButton.cpp
    Interface/BasicCarrat.cpp
    Interface/BasicChat.cpp
    Interface/BasicChatLeftBar.cpp
    Interface/BasicChatRightBody.cpp
    Interface/BasicChatRightBodyEx.cpp
    Interface/BasicComboBox.cpp
    Interface/BasicComboBoxRollOver.cpp
    Interface/BasicEscMenu.cpp
    Interface/BasicGameMenu.cpp
    Interface/BasicHWOptionWindow.cpp
    Interface/BasicInfoView.cpp
    Interface/BasicLevelDisplay.cpp
    Interface/BasicLineBox.cpp
    Interface/BasicLineBoxButton.cpp
    Interface/BasicLineBoxEx.cpp
    Interface/BasicLineBoxSmart.cpp
    Interface/BasicMiniBarGauge.cpp
    Interface/BasicPotionTray.cpp
    Interface/BasicProgressBar.cpp
    Interface/BasicQuickPotionSlot.cpp
    Interface/BasicQuickPotionSlotEx.cpp
    Interface/BasicQuickSkillSlot.cpp
    Interface/BasicQuickSkillSlotEx.cpp
    Interface/BasicScrollBar.cpp
    Interface/BasicScrollBarEx.cpp
    Interface/BasicScrollThumb.cpp
    Interface/BasicScrollThumbFrame.cpp
    Interface/BasicScrollThumbFrameUpdate.cpp
    Interface/BasicSkillTray.cpp
    Interface/BasicTextBox.cpp
    Interface/BasicTextBoxEtc.cpp
    Interface/BasicTextBoxEx.cpp
    Interface/BasicTextBoxSimple.cpp
    Interface/BasicTextButton.cpp
    Interface/BasicTextButtonEx.cpp
    Interface/BasicTextButtonImage.cpp
    Interface/BasicTree.cpp
    Interface/BasicTreeEx.cpp
    Interface/BasicTreeNode.cpp
    Interface/BasicVarTextBox.cpp
    Interface/BasicVarTextBoxItemLink.cpp
    Interface/BikeColorSelect.cpp
    Interface/BikeColorSelectSlot.cpp
    Interface/BikeColorWindow.cpp
    Interface/BlockProgramAlarm.cpp
    Interface/BonusTimeDisplay.cpp
    Interface/BonusTimeGauge.cpp
    Interface/BonusTimeType.cpp
    Interface/BusWindow.cpp
    Interface/Calendar.cpp
    Interface/CarColorSelectSlot.cpp
    Interface/CarColorWindow.cpp
    Interface/CdmRankingDisplay.cpp
    Interface/CdmRankingDisplaySlot.cpp
    Interface/ChangeScaleWindow.cpp
    Interface/ChangeSchoolWindow.cpp
    Interface/CharacterCreateInfo.cpp
    Interface/CharacterCreateInfoClass.cpp
    Interface/CharacterCreateInfoSchool.cpp
    Interface/CharacterCreateInfoSex.cpp
    Interface/CharacterCreatePage.cpp
    Interface/CharacterCreatePageSet.cpp
    Interface/CharacterCreatePageStyle.cpp
    Interface/CharacterCreateRotate.cpp
    Interface/CharacterInfoViewPageStats.cpp
    Interface/CharacterInfoViewPageStatsMark.cpp
    Interface/CharacterInfoViewPageStatsRender.cpp
    Interface/CharacterInfoViewWindow.cpp
    Interface/CharacterWindow/CharacterWindow.cpp
    Interface/CharacterWindow/CharacterWindowChar.cpp
    Interface/CharacterWindow/CharacterWindowCharRender.cpp
    Interface/CharacterWindow/CharacterWindowCharStat.cpp
    Interface/CharacterWindow/CharacterWindowCharStatMark.cpp
    Interface/CharacterWindow/CharacterWindowCharWear.cpp
    Interface/CharacterWindow/CharacterWindowCharWearEx.cpp
    Interface/CharacterWindow/ItemImageCharWear.cpp
    Interface/ChatMacroWindow.cpp
    Interface/ChatShowFlag.cpp
    Interface/ClubAnnounce.cpp
    Interface/ClubBattle.cpp
    Interface/ClubBattleModalWindow.cpp
    Interface/ClubMake.cpp
    Interface/ClubMember.cpp
    Interface/ClubUnion.cpp
    Interface/ClubWindow.cpp
    Interface/CodexWindow/CodexPage.cpp
    Interface/CodexWindow/CodexPageMain.cpp
    Interface/CodexWindow/CodexPageMainSlot.cpp
    Interface/CodexWindow/StudentCodexButton.cpp
    Interface/CodexWindow/StudentCodexWindow.cpp
    Interface/CompetitionNotifyButton.cpp
    Interface/CompetitionNotifyButtonAlarm.cpp
    Interface/CompetitionWindow.cpp
    Interface/ConftConfirm.cpp
    Interface/ConftDisplayMan.cpp
    Interface/ConftModalWindow.cpp
    Interface/ConftModalWindowMsg.cpp
    Interface/CountMsg.cpp
    Interface/CrowTargetInfo.cpp
    Interface/CrowTargetInfoNpc.cpp
    Interface/CrowTargetInfoPlayer.cpp
    Interface/CWRankingDisplay/CWRankingDisplay.cpp
    Interface/DamageDisplay.cpp
    Interface/DamageDisplayMan.cpp
    Interface/DayBox.cpp
    Interface/DialogueWindow.cpp
    Interface/DialogueWindowRenewal.cpp
    Interface/EquipmentLockEnableWindow.cpp
    Interface/EquipmentLockInputWindow.cpp
    Interface/EquipmentLockRecoverWindow.cpp
    Interface/EscMenuOpen.cpp
    Interface/ExtraNotice.cpp
    Interface/FaceStyleCard.cpp
    Interface/FItemFactTimeDisplay.cpp
    Interface/ForgotPassChangePage.cpp
    Interface/ForgotPassPage.cpp
    Interface/FriendWindow.cpp
    Interface/FriendWindowBlockPage.cpp
    Interface/FriendWindowNormalPage.cpp
    Interface/GambleAgainBox.cpp
    Interface/GambleAnimationBox.cpp
    Interface/GambleBox.cpp
    Interface/GambleResultBox.cpp
    Interface/GambleResultEvenBox.cpp
    Interface/GambleResultOddBox.cpp
    Interface/GambleSelectBox.cpp
    Interface/GamePlayOption.cpp
    Interface/GamePlayOptionMsg.cpp
    Interface/GameStats.cpp
    Interface/GameTextControl.cpp
    Interface/GameTimeConvertUI.cpp
    Interface/GarbageInventoryPage.cpp
    Interface/GarbageInventoryWindow.cpp
    Interface/GatherGauge.cpp
    Interface/GenderChangeWindow.cpp
    Interface/GlobalRankingWindow/GlobalRankingPage.cpp
    Interface/GlobalRankingWindow/GlobalRankingPageSlot.cpp
    Interface/GlobalRankingWindow/GlobalRankingWindow.cpp
    Interface/HairColorCard.cpp
    Interface/HairStyleCard.cpp
    Interface/HeadChatDisplay.cpp
    Interface/HeadChatDisplayMan.cpp
    Interface/HelpDataMan.cpp
    Interface/HelpWindow.cpp
    Interface/HelpWindowWeb.cpp
    Interface/InBoxWindow.cpp
    Interface/InfoBoxContents.cpp
    Interface/InnerInterface.cpp
    Interface/InnerInterfaceModalMsg.cpp
    Interface/InnerInterfaceMsg.cpp
    Interface/InnerInterfaceSimple.cpp
    Interface/InventoryLockEnableWindow.cpp
    Interface/InventoryLockInputWindow.cpp
    Interface/InventoryLockRecoverWindow.cpp
    Interface/InventoryUI.cpp
    Interface/InventoryUIBank.cpp
    Interface/InventoryUIInven.cpp
    Interface/InventoryUIWishList.cpp
    Interface/InventoryUI_ItemMix.cpp
    Interface/InventoryUI_ItemMixInven.cpp
    Interface/InventoryUI_Rebuild.cpp
    Interface/InventoryUI_RebuildInven.cpp
    Interface/InventoryUI_Trade.cpp
    Interface/InventoryUI_TradeInven.cpp
    Interface/InventoryUI_Trash.cpp
    Interface/InventoryUI_TrashInven.cpp
    Interface/ItemBankPage.cpp
    Interface/ItemBankWindow.cpp
    Interface/ItemColorSelectSlot.cpp
    Interface/ItemColorWindow.cpp
    Interface/ItemGarbage.cpp
    Interface/ItemImage.cpp
    Interface/ItemInfoToolTip.cpp
    Interface/ItemMallButton.cpp
    Interface/ItemMallWindow.cpp
    Interface/ItemMallWindowMenu.cpp
    Interface/ItemMallWindowMenuButton.cpp
    Interface/ItemMallWindowMenuPage.cpp
    Interface/ItemMallWindowMenuSlot.cpp
    Interface/ItemMixInventoryPage.cpp
    Interface/ItemMixInventoryWindow.cpp
    Interface/ItemMixWindow.cpp
    Interface/ItemMove.cpp
    Interface/ItemPreviewWindow.cpp
    Interface/ItemPreviewWindowRender.cpp
    Interface/ItemRebuild.cpp
    Interface/ItemRebuildOption.cpp
    Interface/ItemSearchResultWindow.cpp
    Interface/ItemShopIcon.cpp
    Interface/ItemShopIconMan.cpp
    Interface/ItemShopSlot.cpp
    Interface/ItemShopWindow.cpp
    Interface/ItemShopWindowWeb.cpp
    Interface/ItemSlot.cpp
    Interface/ItemSlotEx.cpp
    Interface/ItemSlotEx_Renew.cpp
    Interface/ItemSlotPrivateMarket.cpp
    Interface/ItemSlot_Renew.cpp
    Interface/ItemTransferInventoryPage.cpp
    Interface/ItemTransferInventoryWindow.cpp
    Interface/ItemTransferWindow.cpp
    Interface/KeySettingWindow.cpp
    Interface/LargeMapWindow.cpp
    Interface/LargeMapWindowCheckBox.cpp
    Interface/LargeMapWindowImage.cpp
    Interface/LargeMapWindowInfo.cpp
    Interface/LargeMapWindowMob.cpp
    Interface/LargeMapWindowMobDrop.cpp
    Interface/LargeMapWindowRadio.cpp
    Interface/LargeMapWindowSetting.cpp
    Interface/LargeMapWindowSlotRender.cpp
    Interface/LoadingMapThread.cpp
    Interface/LoadingThread.cpp
    Interface/LobbyTitle.cpp
    Interface/LoginPage.cpp
    Interface/MapMoveDisplay.cpp
    Interface/MapRequireCheck.cpp
    Interface/MarketPage.cpp
    Interface/MarketWindow.cpp
    Interface/MessageWindow.cpp
    Interface/MiniMap.cpp
    Interface/MiniMapInfo.cpp
    Interface/MiniPartySlot.cpp
    Interface/MiniPartyWindow.cpp
    Interface/MobDBWindowItem.cpp
    Interface/MobPreviewWindow.cpp
    Interface/MobPreviewWindowRender.cpp
    Interface/ModalWindow.cpp
    Interface/ModernQuestInfoDone.cpp
    Interface/ModernQuestInfoProg.cpp
    Interface/ModernQuestListDone.cpp
    Interface/ModernQuestListProg.cpp
    Interface/ModernQuestWindow.cpp
    Interface/MultiModeButton.cpp
    Interface/MultiModeButtonImage.cpp
    Interface/NameDisplay.cpp
    Interface/NameDisplayMan.cpp
    Interface/NPCDialoguePage.cpp
    Interface/NPCItemExchangeSlot.cpp
    Interface/NPCItemExchangeWindow.cpp
    Interface/NPCMarketPage.cpp
    Interface/NPCPromotionPage.cpp
    Interface/NPCShopItemSlot.cpp
    Interface/NPCShopWindow.cpp
    Interface/OuterInterface.cpp
    Interface/OuterInterfaceModalMsg.cpp
    Interface/OuterInterfaceMsg.cpp
    Interface/OuterInterfaceSimple.cpp
    Interface/PandoraBoxButton.cpp
    Interface/PandoraBoxItemSlot.cpp
    Interface/PandoraBoxResultsItemSlot.cpp
    Interface/PandoraBoxWindow.cpp
    Interface/PartyBuffInfo.cpp
    Interface/PartyBuffInfoUnit.cpp
    Interface/PartyDisplay.cpp
    Interface/PartyDisplayBuffInfo.cpp
    Interface/PartyDisplayBuffInfoUnit.cpp
    Interface/PartyModalWindow.cpp
    Interface/PartyModalWindowMsg.cpp
    Interface/PartySearch/PartyFinderIcon.cpp
    Interface/PartySearch/PartyFinderSlot.cpp
    Interface/PartySearch/PartyFinderWindow.cpp
    Interface/PartySearch/PartyRequestModalWindow.cpp
    Interface/PartySlot.cpp
    Interface/PartySlotDisplay.cpp
    Interface/PartyWindow.cpp
    Interface/PartyWindowCheckBox.cpp
    Interface/PassKeyboard.cpp
    Interface/PetColorCard.cpp
    Interface/PetQuickSkillSlot.cpp
    Interface/PetQuickSkillSlot2.cpp
    Interface/PetRebirthDialogue.cpp
    Interface/PetSkillImage.cpp
    Interface/PetSkillInfoDisplay.cpp
    Interface/PetSkillInfoDisplay2.cpp
    Interface/PetSkillPage.cpp
    Interface/PetSkillSlot.cpp
    Interface/PetSkillWindow.cpp
    Interface/PetskinMixImage.cpp
    Interface/PetStatus.cpp
    Interface/PetStyleCard.cpp
    Interface/PetWindow.cpp
    Interface/PetWindowRender.cpp
    Interface/PKComboDisplay.cpp
    Interface/PKComboType.cpp
    Interface/PKRankNotification.cpp
    Interface/PKRankNotificationInfo.cpp
    Interface/PlayerRankingButton.cpp
    Interface/PrivateMarketMake.cpp
    Interface/PrivateMarketPage.cpp
    Interface/PrivateMarketSellWindow.cpp
    Interface/PrivateMarketShow.cpp
    Interface/PrivateMarketShowMan.cpp
    Interface/PrivateMarketWindow.cpp
    Interface/ProductButton.cpp
    Interface/ProductWindow.cpp
    Interface/ProductWindowList.cpp
    Interface/ProductWindowProduct.cpp
    Interface/ProductWindowType.cpp
    Interface/ProductWindowTypeBase.cpp
    Interface/PtoPWindow.cpp
    Interface/PVPCaptureTheFlagBattleNotice.cpp
    Interface/PVPCaptureTheFlagHoldIcon.cpp
    Interface/PVPCaptureTheFlagPage.cpp
    Interface/PVPCaptureTheFlagPageBattle.cpp
    Interface/PVPCaptureTheFlagPageHistory.cpp
    Interface/PVPCaptureTheFlagRankingPage.cpp
    Interface/PVPCaptureTheFlagRankingPageSlot.cpp
    Interface/PVPCaptureTheFlagRankings.cpp
    Interface/PVPCaptureTheFlagRebirthDialogue.cpp
    Interface/PVPCaptureTheFlagScore.cpp
    Interface/PVPCaptureTheFlagTopRankings.cpp
    Interface/PVPCaptureTheFlagTopRankingsSlot.cpp
    Interface/PVPSchoolWarsBattleNotice.cpp
    Interface/PVPSchoolWarsPage.cpp
    Interface/PVPSchoolWarsPageBattle.cpp
    Interface/PVPSchoolWarsPageHistory.cpp
    Interface/PVPSchoolWarsRankingPage.cpp
    Interface/PVPSchoolWarsRankingPageSlot.cpp
    Interface/PVPSchoolWarsRankings.cpp
    Interface/PVPSchoolWarsRebirthDialogue.cpp
    Interface/PVPSchoolWarsScore.cpp
    Interface/PVPSchoolWarsTopRankings.cpp
    Interface/PVPSchoolWarsTopRankingsSlot.cpp
    Interface/PVPTyranny2CaptureNotice.cpp
    Interface/PVPTyrannyBattleNotice.cpp
    Interface/PVPTyrannyCaptureNotice.cpp
    Interface/PVPTyrannyPage.cpp
    Interface/PVPTyrannyPageBattle.cpp
    Interface/PVPTyrannyPageHistory.cpp
    Interface/PVPTyrannyPageHistoryBuff.cpp
    Interface/PVPTyrannyRankingPage.cpp
    Interface/PVPTyrannyRankingPageSlot.cpp
    Interface/PVPTyrannyRankings.cpp
    Interface/PVPTyrannyRebirthDialogue.cpp
    Interface/PVPTyrannyTopRankings.cpp
    Interface/PVPTyrannyTopRankingsSlot.cpp
    Interface/PVPTyrannyTowerCapture.cpp
    Interface/PVPTyrannyTowerProgress.cpp
    Interface/QBoxButton.cpp
    Interface/QBoxButtonIcon.cpp
    Interface/QuestAlarm.cpp
    Interface/QuestGiftView.cpp
    Interface/QuestHelper.cpp
    Interface/QuestionItemDisplay.cpp
    Interface/QuestionItemType.cpp
    Interface/QuestList.cpp
    Interface/QuestMain.cpp
    Interface/QuestStep.cpp
    Interface/QuestWindow.cpp
    Interface/RebirthDialogue.cpp
    Interface/RebirthWindow.cpp
    Interface/RebirthWindowButton.cpp
    Interface/RebuildInventoryPage.cpp
    Interface/RebuildInventoryWindow.cpp
    Interface/ReceiveNoteWindow.cpp
    Interface/RegisterPage.cpp
    Interface/SecPassCheckPage.cpp
    Interface/SecPassSetPage.cpp
    Interface/SecurityWindow.cpp
    Interface/SelectCharacterButton.cpp
    Interface/SelectCharacterChangeMail.cpp
    Interface/SelectCharacterChangePass.cpp
    Interface/SelectCharacterChangePin.cpp
    Interface/SelectCharacterInfoPage.cpp
    Interface/SelectCharacterList.cpp
    Interface/SelectCharacterListItem.cpp
    Interface/SelectCharacterPage.cpp
    Interface/SelectCharacterResetPin.cpp
    Interface/SelectCharacterTopUp.cpp
    Interface/SelectChinaAreaPage.cpp
    Interface/SelectServerChannel.cpp
    Interface/SelectServerPage.cpp
    Interface/SelectServerPageTw.cpp
    Interface/SentWindow.cpp
    Interface/ShopItemSearchWindow.cpp
    Interface/ShotCutBox.cpp
    Interface/SimpleHP.cpp
    Interface/SimpleMessageMan.cpp
    Interface/SkillFunc.cpp
    Interface/SkillImage.cpp
    Interface/SkillImage33.cpp
    Interface/SkillInforToolTip.cpp
    Interface/SkillLinkInfoToolTip.cpp
    Interface/SkillPage.cpp
    Interface/SkillSlot.cpp
    Interface/SkillTimeDisplay.cpp
    Interface/SkillTimeUnit.cpp
    Interface/SkillTrayTab.cpp
    Interface/SkillWindow.cpp
    Interface/SkillWindowToTray.cpp
    Interface/SlotCountMsg.cpp
    Interface/SMSSendWindow.cpp
    Interface/StaticUIManager.cpp
    Interface/StorageChargeCard.cpp
    Interface/StorageLockEnableWindow.cpp
    Interface/StorageLockInputWindow.cpp
    Interface/StorageLockRecoverWindow.cpp
    Interface/StoragePage.cpp
    Interface/StorageWindow.cpp
    Interface/StudentRecordButton.cpp
    Interface/StudentRecordWindow.cpp
    Interface/SubMasterSet.cpp
    Interface/SwapImage.cpp
    Interface/SystemBuffTimeDisplay.cpp
    Interface/SystemMessageDisplay.cpp
    Interface/SystemMessageWindow.cpp
    Interface/TargetInfoDisplay.cpp
    Interface/TargetInfoDisplayNpc.cpp
    Interface/TargetInfoDisplayPlayer.cpp
    Interface/TaxiWindow.cpp
    Interface/ThaiCCafeMark.cpp
    Interface/TradeControlPage.cpp
    Interface/TradeInventoryPage.cpp
    Interface/TradeInventoryWindow.cpp
    Interface/TradePage.cpp
    Interface/TradeWindow.cpp
    Interface/UIEditBox.cpp
    Interface/UIEditBoxMan.cpp
    Interface/UIItemInfoLoader.cpp
    Interface/UILeftTopGroup.cpp
    Interface/UIModal.cpp
    Interface/UIMultiEditBox.cpp
    Interface/UIOuterWindow.cpp
    Interface/UISkillInfoLoader.cpp
    Interface/UITextControl.cpp
    Interface/UIWindow.cpp
    Interface/UIWindowBody.cpp
    Interface/UIWindowEx.cpp
    Interface/UIWindowTitle.cpp
    Interface/Util/CheckBox.cpp
    Interface/Util/MessageBox.cpp
    Interface/Util/NpcActionable.cpp
    Interface/Util/RnButton.cpp
    Interface/Util/RnProgressBar.cpp
    Interface/Util/TapSelector.cpp
    Interface/VehicleBoosterDisplay.cpp
    Interface/VehicleStatus.cpp
    Interface/VehicleWindow.cpp
    Interface/VehicleWindowRender.cpp
    Interface/VideoOption.cpp
    Interface/VideoOptionMsg.cpp
    Interface/VNGainSysGauge.cpp
    Interface/VNGainSysInventory.cpp
    Interface/VNGainSysPage.cpp
    Interface/WaitDialogue.cpp
    Interface/WaitServerDialogue.cpp
    Interface/WarningMsg.cpp
    Interface/WeaponDisplay.cpp
    Interface/WriteNoteWindow.cpp
    stdafx.cpp
)

target_include_directories(Lib_ClientUI PRIVATE
    $<$<CONFIG:Release>:
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}/Interface
        ${CMAKE_SOURCE_DIR}/Lib_Engine
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Common
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxCommon
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxCommon9
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/Char
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/EffAni
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/EffKeep
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/EffProj
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/Single
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxFrame
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxOctree
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Meshs
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxSound
        ${CMAKE_SOURCE_DIR}/Lib_Engine/G-Logic
        ${CMAKE_SOURCE_DIR}/Lib_Engine/GUInterface
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Utils
        ${CMAKE_SOURCE_DIR}/Lib_Helper
        ${CMAKE_SOURCE_DIR}/Lib_Network
        ${CMAKE_SOURCE_DIR}/Lib_Client
        ${CMAKE_SOURCE_DIR}/Lib_Client/G-Logic
        ${CMAKE_SOURCE_DIR}/Lib_Client/NpcTalk
        ${CMAKE_SOURCE_DIR}/Tik/DXInclude
        ${CMAKE_SOURCE_DIR}/Tik/DXLib
        ${CMAKE_SOURCE_DIR}/Tik/Include
        ${CMAKE_SOURCE_DIR}/Tik/Library
        ${CMAKE_SOURCE_DIR}/Tik/TbbLib
    >
    $<$<CONFIG:Debug>:
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/ControlExUI
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/InnerUI
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/LoaderUI
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/OuterUI
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/TextUI
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/Common
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxCommon
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxCommon9
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxEffect
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxLand
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxMeshs
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxTools
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/G-Logic
        ${CMAKE_SOURCE_DIR}/Lib_EngineSound/Sources
        ${CMAKE_SOURCE_DIR}/Lib_EngineSound/Sources/DxSound
        ${CMAKE_SOURCE_DIR}/Lib_EngineSound/Sources/ogg
        ${CMAKE_SOURCE_DIR}/Lib_EngineSound/Sources/vorbis
        ${CMAKE_SOURCE_DIR}/Lib_EngineUI/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Helper/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Helper/Sources/ExLibs
        ${CMAKE_SOURCE_DIR}/[Lib]__NetClient/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Network/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources/DbAction
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources/G-Logic
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources/G-Logic/Client
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources/G-Logic/Data
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources/G-Logic/GLMsg
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources/G-Logic/Npc
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources/G-Logic/Quest
        ${CMAKE_SOURCE_DIR}/Lib_Client/Sources/G-Logic/Server
        ${CMAKE_SOURCE_DIR}/Dependency/common
        ${CMAKE_SOURCE_DIR}/Dependency/directx
        ${CMAKE_SOURCE_DIR}/Dependency/lzo
        ${CMAKE_SOURCE_DIR}/Dependency/NetGlobal
        ${CMAKE_SOURCE_DIR}/Dependency/tbblib/Include
    >
)

target_compile_definitions(Lib_ClientUI PRIVATE
    WIN32
    _LIB
    $<$<CONFIG:Debug>:_DEBUG>
    $<$<CONFIG:Release>:NDEBUG>
)

if(MSVC)
    target_compile_options(Lib_ClientUI PRIVATE
        "SHELL:/Yu\"stdafx.h\""
        $<$<CONFIG:Debug>:/W3>
        $<$<CONFIG:Debug>:/Od>
        $<$<CONFIG:Release>:/W0>
        $<$<CONFIG:Release>:/O2>
        /MP
    )

    set_source_files_properties(stdafx.cpp PROPERTIES
        COMPILE_FLAGS "/Yc\"stdafx.h\""
    )

    set_target_properties(Lib_ClientUI PROPERTIES
        OUTPUT_NAME "$<$<CONFIG:Debug>:RanClientUID>$<$<CONFIG:Release>:Lib_ClientUI>"
        MFC_FLAG 2
    )
endif()
