add_library(Lib_Client STATIC
    ClientApex.cpp
    DbActionLogic.cpp
    DbActionLogicClub.cpp
    DbActionLogicEquipmentLock.cpp
    DbActionLogicInventoryLock.cpp
    DbActionLogicLog.cpp
    DbActionLogicPet.cpp
    DbActionLogicShop.cpp
    DbActionLogicSMS.cpp
    DbActionLogicStorageLock.cpp
    DbActionLogicVehicle.cpp
    DxCharSham.cpp
    DxGameStage.cpp
    DxGlobalStage.cpp
    dxincommand.cpp
    DxLobyStage.cpp
    DxLobyStageCreateChar.cpp
    DxLobyStageSelectChar.cpp
    DxParamSet.cpp
    DxServerInstance.cpp
    G-Logic/Emoticon.cpp
    G-Logic/GLActivity.cpp
    G-Logic/GLActivityData.cpp
    G-Logic/GLActivityDefine.cpp
    G-Logic/GLAgentServer.cpp
    G-Logic/GLAgentServerEx.cpp
    G-Logic/GLAgentServerMsg.cpp
    G-Logic/GLAGLandMan.cpp
    G-Logic/GLAnyPet.cpp
    G-Logic/GLAnySummon.cpp
    G-Logic/GLAnySummonMsg.cpp
    G-Logic/GLARoundSlot.cpp
    G-Logic/GLAutoLevel.cpp
    G-Logic/GLAutoLevelMan.cpp
    G-Logic/GLBusData.cpp
    G-Logic/GLBusList.cpp
    G-Logic/GLBusStation.cpp
    G-Logic/GLChar.cpp
    G-Logic/GLCharacter.cpp
    G-Logic/GLCharacterAllianceMsg.cpp
    G-Logic/GLCharacterClubBattleMsg.cpp
    G-Logic/GLCharacterClubMsg.cpp
    G-Logic/GLCharacterConfrontMsg.cpp
    G-Logic/GLCharacterMiniGameMsg.cpp
    G-Logic/GLCharacterMsg.cpp
    G-Logic/GLCharacterQuestMsg.cpp
    G-Logic/GLCharacterSkill.cpp
    G-Logic/GLCharacterSkillTarget.cpp
    G-Logic/GLCharActivity.cpp
    G-Logic/GLCharactorReq.cpp
    G-Logic/GLCharactorReq2.cpp
    G-Logic/GLCharAG.cpp
    G-Logic/GLCharAGClub.cpp
    G-Logic/GLCharClient.cpp
    G-Logic/GLCharClubMsg.cpp
    G-Logic/GLCharCodex.cpp
    G-Logic/GLCharData.cpp
    G-Logic/GLCharDataActivity.cpp
    G-Logic/GLCharDataCodex.cpp
    G-Logic/GLCharDataLoad.cpp
    G-Logic/GLCharDataPandora.cpp
    G-Logic/GLCharDefine.cpp
    G-Logic/GLCharEx.cpp
    G-Logic/GLCharInvenMsg.cpp
    G-Logic/GLCharInvenMsg2.cpp
    G-Logic/GLCharMsg.cpp
    G-Logic/GLCharPetMsg.cpp
    G-Logic/GLCharPMarketMsg.cpp
    G-Logic/GLCharQuest.cpp
    G-Logic/GLCharQuestMsg.cpp
    G-Logic/GLCharSkillMsg.cpp
    G-Logic/GLCharSkillMsg_SetTarget.cpp
    G-Logic/GLCharStorageMsg.cpp
    G-Logic/GLClubDeathMatch.cpp
    G-Logic/GLClubMan.cpp
    G-Logic/GLCodex.cpp
    G-Logic/GLCodexData.cpp
    G-Logic/GLCodexDefine.cpp
    G-Logic/GLCommentFile.cpp
    G-Logic/GLContrlMsg.cpp
    G-Logic/GLContrlPcMsg.cpp
    G-Logic/GLCrow.cpp
    G-Logic/GLCrowClient.cpp
    G-Logic/GLCrowData.cpp
    G-Logic/GLCrowDataAction.cpp
    G-Logic/GLCrowDataAttack.cpp
    G-Logic/GLCrowDataBasic.cpp
    G-Logic/GLCrowDataGen.cpp
    G-Logic/GLCrowDataItemExchange.cpp
    G-Logic/GLCrowDataLoad.cpp
    G-Logic/GLCrowDataNPCShop.cpp
    G-Logic/GLCrowGenerateReward.cpp
    G-Logic/GLCrowReAction.cpp
    G-Logic/GLCrowRenList.cpp
    G-Logic/GLCrowSkill.cpp
    G-Logic/GLCrowSkillTarget.cpp
    G-Logic/GLDescriptionFile.cpp
    G-Logic/GLEventProc.cpp
    G-Logic/GLFactData.cpp
    G-Logic/GLFactEffect.cpp
    G-Logic/GLFreePK.cpp
    G-Logic/GLFriendClient.cpp
    G-Logic/GLGaeaClient.cpp
    G-Logic/GLGaeaServer.cpp
    G-Logic/GLGaeaServerEx.cpp
    G-Logic/GLGaeaServerMsg.cpp
    G-Logic/GLGuidance.cpp
    G-Logic/GLInventory.cpp
    G-Logic/GLItem.cpp
    G-Logic/GLItemBasic.cpp
    G-Logic/GLItemBox.cpp
    G-Logic/GLItemDef.cpp
    G-Logic/GLItemDef2.cpp
    G-Logic/GLItemDrug.cpp
    G-Logic/GLItemGenerate.cpp
    G-Logic/GLItemGrinding.cpp
    G-Logic/GLItemLink.cpp
    G-Logic/GLITEMLMT.cpp
    G-Logic/GLItemMan.cpp
    G-Logic/GLItemMix.cpp
    G-Logic/GLItemMixMan.cpp
    G-Logic/GLItemPet.cpp
    G-Logic/GLItemPetSkin.cpp
    G-Logic/GLItemQuestion.cpp
    G-Logic/GLItemRandomBox.cpp
    G-Logic/GLItemRandomOption.cpp
    G-Logic/GLItemRVCard.cpp
    G-Logic/GLItemSkillBook.cpp
    G-Logic/GLItemSuit.cpp
    G-Logic/GLItemVehicle.cpp
    G-Logic/GLLandMan.cpp
    G-Logic/GLLandManClient.cpp
    G-Logic/GLLandManSet.cpp
    G-Logic/GLLandMark.cpp
    G-Logic/GLLevelEtcFunction.cpp
    G-Logic/GLLevelFile.cpp
    G-Logic/GLLevelFileSaveLoad.cpp
    G-Logic/GLLevelHead.cpp
    G-Logic/GLLevelRequire.cpp
    G-Logic/GLMapAxisInfo.cpp
    G-Logic/GLMapList.cpp
    G-Logic/GLMapNode.cpp
    G-Logic/GLMaterial.cpp
    G-Logic/GLMaterialClient.cpp
    G-Logic/GLMobSchedule.cpp
    G-Logic/GLMobScheduleSaveLoad.cpp
    G-Logic/GLMoney.cpp
    G-Logic/GLNote.cpp
    G-Logic/GLogicData.cpp
    G-Logic/GLogicDataLoad.cpp
    G-Logic/GLogicEx.cpp
    G-Logic/GLogicExNPC.cpp
    G-Logic/GLogixExPC.cpp
    G-Logic/GLParty.cpp
    G-Logic/GLPartyClient.cpp
    G-Logic/GLPartyField.cpp
    G-Logic/GLPartyFieldMan.cpp
    G-Logic/GLPartyMan.cpp
    G-Logic/GLPet.cpp
    G-Logic/GLPetClient.cpp
    G-Logic/GLPetClientMsg.cpp
    G-Logic/GLPetClientReq.cpp
    G-Logic/GLPetClientSkill.cpp
    G-Logic/GLPetField.cpp
    G-Logic/GLPetFieldMsg.cpp
    G-Logic/GLPrivateMarket.cpp
    G-Logic/GLProductDefine.cpp
    G-Logic/GLPVPCaptureTheFlag.cpp
    G-Logic/GLPVPCaptureTheFlagAgent.cpp
    G-Logic/GLPVPCaptureTheFlagAgentMapMove.cpp
    G-Logic/GLPVPCaptureTheFlagAgentMsg.cpp
    G-Logic/GLPVPCaptureTheFlagAgentRegister.cpp
    G-Logic/GLPVPCaptureTheFlagClient.cpp
    G-Logic/GLPVPCaptureTheFlagClientFlag.cpp
    G-Logic/GLPVPCaptureTheFlagClientMSG.cpp
    G-Logic/GLPVPCaptureTheFlagField.cpp
    G-Logic/GLPVPCaptureTheFlagFieldFlag.cpp
    G-Logic/GLPVPCaptureTheFlagFieldMSG.cpp
    G-Logic/GLPVPCaptureTheFlagFieldRanking.cpp
    G-Logic/GLPVPSchoolWars.cpp
    G-Logic/GLPVPSchoolWarsAgent.cpp
    G-Logic/GLPVPSchoolWarsAgentMapMove.cpp
    G-Logic/GLPVPSchoolWarsAgentMsg.cpp
    G-Logic/GLPVPSchoolWarsAgentRegister.cpp
    G-Logic/GLPVPSchoolWarsClient.cpp
    G-Logic/GLPVPSchoolWarsClientMSG.cpp
    G-Logic/GLPVPSchoolWarsField.cpp
    G-Logic/GLPVPSchoolWarsFieldMSG.cpp
    G-Logic/GLPVPSchoolWarsFieldRanking.cpp
    G-Logic/GLPVPTyranny.cpp
    G-Logic/GLPVPTyrannyAgent.cpp
    G-Logic/GLPVPTyrannyAgentMapMove.cpp
    G-Logic/GLPVPTyrannyAgentMSG.cpp
    G-Logic/GLPVPTyrannyAgentRegister.cpp
    G-Logic/GLPVPTyrannyAgentTower.cpp
    G-Logic/GLPVPTyrannyClient.cpp
    G-Logic/GLPVPTyrannyClientMSG.cpp
    G-Logic/GLPVPTyrannyField.cpp
    G-Logic/GLPVPTyrannyFieldMSG.cpp
    G-Logic/GLPVPTyrannyFieldRanking.cpp
    G-Logic/GLQuest.cpp
    G-Logic/GLQuestGenItem.cpp
    G-Logic/GLQuestMan.cpp
    G-Logic/GLQuestPlay.cpp
    G-Logic/GLQuestStart.cpp
    G-Logic/GLQuestStep.cpp
    G-Logic/GLSchoolFreePK.cpp
    G-Logic/GLSkill.cpp
    G-Logic/GLSkillApply.cpp
    G-Logic/GLSkillBasic.cpp
    G-Logic/GLSkillDefine.cpp
    G-Logic/GLSkillExData.cpp
    G-Logic/GLSkillLearn.cpp
    G-Logic/GLSkillSpecial.cpp
    G-Logic/GLSkillToolTip.cpp
    G-Logic/GLStrikeSelector.cpp
    G-Logic/GLStringTable.cpp
    G-Logic/GLSummon.cpp
    G-Logic/GLSummonClient.cpp
    G-Logic/GLSummonClientMsg.cpp
    G-Logic/GLSummonData.cpp
    G-Logic/GLSummonDef.cpp
    G-Logic/GLSummonField.cpp
    G-Logic/GLSummonFieldMsg.cpp
    G-Logic/GLSummonSkill.cpp
    G-Logic/GLTaxiData.cpp
    G-Logic/GLTaxiStation.cpp
    G-Logic/GLTrade.cpp
    G-Logic/GLTradeClient.cpp
    G-Logic/GLVEHICLE.cpp
    G-Logic/stl_Func.cpp
    NpcTalk/NpcDialogue.cpp
    NpcTalk/NpcDialogueCase.cpp
    NpcTalk/NpcDialogueSet.cpp
    NpcTalk/NpcTalk.cpp
    NpcTalk/NpcTalkCondition.cpp
    NpcTalk/NpcTalkControl.cpp
    stdafx.cpp
)

target_include_directories(Lib_Client PRIVATE
    $<$<CONFIG:Release>:
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}/G-Logic
        ${CMAKE_CURRENT_SOURCE_DIR}/NpcTalk
        ${CMAKE_SOURCE_DIR}/Lib_Engine
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Common
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxCommon
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxCommon9
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/Char
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/EffAni
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/EffKeep
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/EffProj
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxEffect/Single
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxFrame
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxOctree
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Meshs
        ${CMAKE_SOURCE_DIR}/Lib_Engine/DxSound
        ${CMAKE_SOURCE_DIR}/Lib_Engine/G-Logic
        ${CMAKE_SOURCE_DIR}/Lib_Engine/GUInterface
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Utils
        ${CMAKE_SOURCE_DIR}/Lib_Helper
        ${CMAKE_SOURCE_DIR}/Lib_Network
        ${CMAKE_SOURCE_DIR}/Lib_ClientUI/Interface
        ${CMAKE_SOURCE_DIR}/Tik/DXInclude
        ${CMAKE_SOURCE_DIR}/Tik/DXLib
        ${CMAKE_SOURCE_DIR}/Tik/Include
        ${CMAKE_SOURCE_DIR}/Tik/Library
        ${CMAKE_SOURCE_DIR}/Tik/TbbLib
    >
    $<$<CONFIG:Debug>:
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/DbAction
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/G-Logic
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/G-Logic/Client
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/G-Logic/Data
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/G-Logic/GLMsg
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/G-Logic/Npc
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/G-Logic/Quest
        ${CMAKE_CURRENT_SOURCE_DIR}/Sources/G-Logic/Server
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/Common
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxCommon
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxCommon9
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxEffect
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxLand
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxMeshs
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/DxTools
        ${CMAKE_SOURCE_DIR}/Lib_Engine/Sources/G-Logic
        ${CMAKE_SOURCE_DIR}/Lib_EngineSound/Sources
        ${CMAKE_SOURCE_DIR}/Lib_EngineSound/Sources/DxSound
        ${CMAKE_SOURCE_DIR}/Lib_EngineSound/Sources/ogg
        ${CMAKE_SOURCE_DIR}/Lib_EngineSound/Sources/vorbis
        ${CMAKE_SOURCE_DIR}/Lib_Helper/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Helper/Sources/ExLibs
        ${CMAKE_SOURCE_DIR}/[Lib]__NetClient/Sources
        ${CMAKE_SOURCE_DIR}/Lib_Network/Sources
        ${CMAKE_SOURCE_DIR}/Lib_ClientUI/Sources/ControlExUI
        ${CMAKE_SOURCE_DIR}/Lib_ClientUI/Sources/InnerUI
        ${CMAKE_SOURCE_DIR}/Lib_ClientUI/Sources/LoaderUI
        ${CMAKE_SOURCE_DIR}/Lib_ClientUI/Sources/OuterUI
        ${CMAKE_SOURCE_DIR}/Lib_ClientUI/Sources/TextUI
        ${CMAKE_SOURCE_DIR}/Dependency/common
        ${CMAKE_SOURCE_DIR}/Dependency/directx
        ${CMAKE_SOURCE_DIR}/Dependency/lzo
        ${CMAKE_SOURCE_DIR}/Dependency/NetGlobal
        ${CMAKE_SOURCE_DIR}/Dependency/tbblib/Include
    >
)

target_compile_definitions(Lib_Client PRIVATE
    WIN32
    _LIB
    $<$<CONFIG:Debug>:_DEBUG>
    $<$<CONFIG:Release>:NDEBUG>
)

if(MSVC)
    target_compile_options(Lib_Client PRIVATE
        "SHELL:/Yu\"stdafx.h\""
        $<$<CONFIG:Debug>:/W3>
        $<$<CONFIG:Debug>:/Od>
        $<$<CONFIG:Release>:/W0>
        $<$<CONFIG:Release>:/O2>
        $<$<CONFIG:Release>:/Gy->
        $<$<CONFIG:Release>:/Oi->
        $<$<CONFIG:Release>:/Ob1>
        $<$<CONFIG:Release>:/Oy>
        $<$<CONFIG:Release>:/GF>
        $<$<CONFIG:Release>:/Gm->
        $<$<CONFIG:Release>:/GS->
        /MP
    )

    set_source_files_properties(stdafx.cpp PROPERTIES
        COMPILE_FLAGS "/Yc\"stdafx.h\""
    )

    set_target_properties(Lib_Client PROPERTIES
        OUTPUT_NAME "$<$<CONFIG:Debug>:RanClientD>$<$<CONFIG:Release>:Lib_Client>"
        MFC_FLAG 2
    )
endif()
